### ISSUE TITLE
Issues buying/selling enchants on books.

### ISSUE THREAD

**Issue by EDGRRRRs** [HTTPStanley/DivinityEconomy#53]
**Describe the bug**
This bug prevents the user from buying/selling enchants from books.

**To Reproduce**
1. Hold enchanted book.
2. /ebuy || /esell <enchant> <level>
3. See error

**Expected behavior**
The plugin should allow the user to buy and sell enchants for/from books.

**Context**
Server Version: 1.19.3
Server Type(Spigot/Paper): Spigot/Paper
Additional Information: None required.

**Comment by HTTPStanley** [comment]
Fixed as of a5c888a.
