### ISSUE TITLE
money prefix isn't used accurately.

### ISSUE THREAD

**Issue by UnknownVariables-here** [HTTPStanley/DivinityEconomy#65]
**Describe the bug**
Checking the value of an Item doesn't show the set currency prefix.

**To Reproduce**
1. Set the money prefix in Config.yml to something like 'Banana ' or 'V ' 
2. Save the config then restart the server
3. Hop on the server and type /value pufferfish 
4. itll show the Euro symbol instead of whatevers set in the config

**Expected behavior**
Expected that itll show the money prefix set in the config

**Screenshots**
![image](https://github.com/HTTPStanley/DivinityEconomy/assets/77986568/0df9efe7-657a-48e8-8616-8edb9cf15f0b)

**Context**
Server Version: 1.20.1
Server Type(Spigot/Paper): Purpur
Additional Information: NA

**Comment by HTTPStanley** [comment]
Fixed as of 94f5d5c
