### ISSUE TITLE
No instructions on disabling price changing or how to change prices of items.

### ISSUE THREAD

**Issue by johnwvin** [HTTPStanley/DivinityEconomy#70]
I have navigated all yml files and found nothing. You state this is possible and give no instructions on how.

**Comment by HTTPStanley** [comment]
Hi Johnwvin,

Firstly I appreciate that there may be missing documentation for this, you see when working on something for so many years, everything seems obvious and it's hard to know what to and what not to write down for others! My apologies.

Secondly, item prices are calculated on-demand. Prices are not stored in files as this cannot be used to create a dynamic deterministic pricing model. Instead, quantities are stored in the file. This value represents how much of an item is available in the market.

Here is the gist:

To change the prices, you must change the quantities. The more items, the cheaper, the less items, the more expensive.

You can view item information with, for example dirt, /iteminfo dirt
You can find the value of dirt using /value dirt
You can set the quantity of dirt using /setstock dirt <amount>
You can set the price of dirt (this uses a reverse calculation to find the correct quantity) /setvalue dirt <amount>
Although an admission on my part is that the /setvalue command is current broken.

Note: Do note change configs whilst the plugin is on, it will not load the new values AND will overwrite the file after shutdown. The plugin uses a smart caching algorithm to make all this maths and stuff extremely fast! But doesn't support quality of life stuff like hot-swapping configs :(

[Any more questions, please hop on our discord!](https://discord.com/invite/K7DY6UD)

**Comment by HTTPStanley** [comment]
Latest update solves issue of lacking documentation and broken /setvalue https://modrinth.com/plugin/divinity-economy/version/3.5.1
